    - name: Analisis de calidad con SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
        args: >
          -Dsonar.organization=claudiasn
          -Dsonar.projectKey=claudiasn_practica4-integracion-continua
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

