    - name: Empaquetar artefacto
      run: mvn -B package

    - name: Subir artefacto generado
      uses: actions/upload-artifact@v4
      with:
        name: artefacto-maven
        path: target/*.jar
