name: Integracion Continua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: "17"
        distribution: "temurin"

    - name: Compilar y ejecutar tests
      run: mvn -B clean verify

    # ESCANEO DE SONARCLOUD
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v2
      with:
        args: >
          -Dsonar.projectKey=claudiasn_practica4-integracion-continua
          -Dsonar.organization=claudiasn
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.java.binaries=target/classes
          -Dsonar.qualitygate.wait=true

    # ESTA PARTE SOLO SE EJECUTA SI EL QUALITY GATE SE APRUEBA
    - name: Empaquetar artefacto
      if: ${{ success() }}
      run: mvn -B package

    - name: Subir artefacto generado
      if: ${{ success() }}
      uses: actions/upload-artifact@v4
      with:
        name: artefacto-maven
        path: target/*.jar
