name: Integracion Continua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Configurar Java 17
      uses: actions/setup-java@v4
      with:
        java-version: "17"
        distribution: "temurin"

    - name: Compilar y ejecutar tests
      run: mvn -B clean verify

      - name: Analisis con SonarCloud
      run: |
        mvn -B clean verify sonar:sonar \
          -Dsonar.projectKey=claudiasn_practica4-integracion-continua \
          -Dsonar.organization=claudiasn \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}


    - name: Empaquetar artefacto
      run: mvn -B package

    - name: Subir artefacto generado
      uses: actions/upload-artifact@v4
      with:
        name: artefacto-maven
        path: target/*.jar
