name: Integración Continua

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Requerido por SonarCloud

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Compilar y ejecutar tests
        run: mvn -B verify

      - name: Análisis de calidad con SonarCloud
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
          -Dsonar.projectKey=claudiasn_practica4-integracion-continua \
          -Dsonar.organization=claudiasn \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Empaquetar artefacto
        run: mvn -B package

      - name: Subir artefacto generado
        uses: actions/upload-artifact@v4
        with:
          name: artefacto-maven
          path: target/*.jar
